export const FILTER_DATA = [
  {
    title: "Các bộ lọc phổ biến",
    options: [
      { name: "4 sao" },
      { name: "Hồ bơi" },
      { name: "WiFi miễn phí" },
      { name: "Trung tâm Spa & chăm sóc sức khoẻ" },
      { name: "Ban công" },
      { name: "Phòng tắm riêng" },
      { name: "Bể sục" },
      { name: "Kitchenette" },
    ],
  },
  {
    title: "Các chứng chỉ",
    options: [{ name: "Chứng chỉ bền vững" }],
  },
  {
    title: "Thương hiệu",
    options: [
      { name: "OYO Rooms" },
      { name: "VBA Hospitality Group" },
      { name: "Somerset" },
      { name: "Belvilla" },
      { name: "Muong Thanh Hospitality" },
      { name: "InterContinental Hotels & Resorts" },
    ],
  },
  {
    title: "Tiện nghi",
    options: [
      { name: "WiFi miễn phí" },
      { name: "Nhà hàng" },
      { name: "Dịch vụ phòng" },
      { name: "Lễ tân 24 giờ" },
      { name: "Trung tâm thể dục" },
      { name: "Trung tâm Spa & chăm sóc sức khoẻ" },
      { name: "Hồ bơi" },
      { name: "Quầy Bar" },
      { name: "Chỗ đỗ xe" },
      { name: "Quầy tour" },
      { name: "Shared kitchen" },
      { name: "Laundry" },
      { name: "Sky bar" },
      { name: "Beach access" },
      { name: "Garden" },
      { name: "Terrace" },
    ],
  },
  {
    title: "Tiện nghi phòng",
    options: [
      { name: "Ban công" },
      { name: "Hồ bơi riêng" },
      { name: "Nhìn ra biển" },
      { name: "Phòng tắm riêng" },
      { name: "Bể sục" },
      { name: "Kitchenette" },
      { name: "Common area" },
      { name: "Căn hộ" },
      { name: "Phòng gia đình" },
    ],
  },
  {
    title: "Điểm đánh giá của khách",
    options: [
      { name: "Tuyệt hảo: 9 điểm trở lên" },
      { name: "Rất tốt: 8 điểm trở lên" },
      { name: "Tốt: 7 điểm trở lên" },
      { name: "Dễ chịu: 6 điểm trở lên" },
    ],
  },
  {
    title: "Loại chỗ ở",
    options: [
      { name: "Căn hộ" },
      { name: "Chỗ nghỉ nhà dân" },
      { name: "Nhà khách" },
      { name: "Nhà trọ" },
      { name: "Nhà nghỉ B&B" },
      { name: "Biệt thự" },
      { name: "Nhà nghỉ mát" },
      { name: "Khách sạn tình nhân" },
      { name: "Khách sạn khoang ngủ" },
      { name: "Resort" },
      { name: "Khu cắm trại" },
      { name: "Nhà nghỉ giữa thiên nhiên" },
    ],
  },
];