export const AMENITIES_MAP = {
  "WiFi miễn phí": "WiFi",
  "Nhà hàng": "Restaurant",
  "Dịch vụ phòng": "Room service",
  "Lễ tân 24 giờ": "24h front desk",
  "Trung tâm thể dục": "Fitness center",
  "Trung tâm Spa & chăm sóc sức khoẻ": "Spa",
  "Hồ bơi": "Swimming pool",
  "Ban công": "Balcony",
  "Căn hộ": "Apartment",
  "Chỗ đỗ xe": "Parking",
  "Bể sục": "Jacuzzi",
  "Phòng tắm riêng": "Private bathroom",
  "Nhìn ra biển": "Sea view",
  "Quầy Bar": "Bar",
  "Quầy tour": "Tour desk",
  "Family rooms": "Family rooms",
  "Kitchenette": "Kitchenette",
  "Shared kitchen": "Shared kitchen",
  "Common area": "Common area",
  "Laundry": "Laundry",
  "Sky bar": "Sky bar",
  "Beach access": "Beach access",
  "Private pool": "Private pool",
  "Garden": "Garden",
  "Terrace": "Terrace",
  "Spa": "Spa",
};